sudo: required
dist: xenial
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install aria2 zip unzip check -qq
script:
- source ./env.sh
- "${DLR} ${ROOTFS_URL} -o ${ROOTFS_FN}"
- "${DLR} ${FRTCP_URL} -o ${FRTCP_FN}"
- 
- sudo tar -zxpf ${ROOTFS_FN}
- cd root.x86_64
- sudo cp -bf ../mirrorlist ./etc/pacman.d/mirrorlist
- sudo cp -bf ../pacman.conf.nosig ./etc/pacman.conf
- sudo cp -bf ../sudoers ./etc/sudoers
- sudo sed -i -e "s/#en_US.UTF-8/en_US.UTF-8/" ./etc/locale.gen
- echo "LANG=en_US.UTF-8" | sudo tee ./etc/locale.conf
- sudo ln -sf /etc/locale.conf ./etc/default/locale
- sudo cp -f ../${FRTCP_FN} ./root/
- sudo cp -f /etc/resolv.conf ./etc/resolv.conf
- sudo mv -f ./etc/mtab ./etc/mtab.bak
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- 
- sudo mount -t proc proc proc/
- sudo mount --bind /sys sys
- 
- sudo chroot . /usr/bin/pacman -Syu --noconfirm ${PAC_PKGS}
- sudo chmod u+s ./usr/bin/ping
- sudo rm -rf ./etc/mtab
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- sudo chroot . /usr/bin/locale-gen
- yes | sudo chroot . /usr/bin/pacman -U /root/${FRTCP_FN}
- yes | sudo chroot . /usr/bin/pacman -Scc
- 
- sudo umount ./{sys,proc}
- sudo mv -f ./etc/mtab.bak ./etc/mtab
- sudo cp -f ../pacman.conf ./etc/pacman.conf
- echo "# This file was automatically generated by WSL. To stop automatic generation
  of this file, remove this line." | sudo tee ./etc/resolv.conf
- 
- sudo rm -rf `sudo find ./root/ -type f`
- sudo rm -rf `sudo find ./var/cache/pacman/pkg/ -type f`
- 
- sudo tar -zcpf ../rootfs.tar.gz *
- sudo chown `id -un` ../rootfs.tar.gz
- cd ..
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: oRP7cKvBQLczKeWXar541h05aUMGTHToe51Et14enf6JDVnXdVC917UjuODJ90dPwG2CNfm4Lei8iG69cnDMk/4Yis3kTKSs4MDEh+l0xOM7fkLWx4+rzkoaotFC1lD/2wl19/rPGf8BEjDrRNo9tWfj0IVkQu6z3qnAqfxZOIeMJmxJS/iOqCQpzeJpqevHHn1PjR6jrCNfjt+uAUpi+0mbqg0Coj+jeNx8vk1KZZp3qDf+3XjnaRDQYQRzEX4s4B9k41Uac7nvMKTw/xHd7cEwh8+tfttC8zy/BYWZ1MHvo0I4Bt3Cz1KoK7MpcbBuwD8vNhKoBZzCnYL1JOQ6xomRrfQjLFnRUYOsQVYrE3BQnMyDTaWE7IQ1+gaEHTqgD+Fj5zuEJo5T23n/iLPZ6vE0y4Exr032QxDAFHnWhx5Lb7vekgsNmIELzAlbbuO094W+Ng1/hAOyPmE5koSf2eri7mpb8RFWUYnuMDhLq6nD+9PVef2pvdqW9T/s3Cu6CGqope/rsuBxFp8XBAale4uPF16ZWMOaqeF4Jn20wP6NM/LdLp6EoM8E20lCO/AKJoI/GWRSiSfwCyi03umut38KtDwcxGmHfyqJnW9BE+AiwWGUcANNW5YlTijOWksBNxIxFmQWuEKkFy3LZ45rApvbOoWZ0F70QyPQhKm4r3o=
  file: rootfs.tar.gz
  on:
    repo: wkmtty/ArchWSL-FS
    tags: true
    all_branches: true
  skip_cleanup: true
